FROM postgres:16

# Switch to root for installing dependencies
USER root

# Install dependencies for Patroni
RUN apt-get update && apt-get install -y \
    python3-psycopg2 patroni procps && \
    apt-get clean

# Revert to the default postgres user
USER postgres

# Expose PostgreSQL and Patroni API ports
EXPOSE 5432 8008

# Set the default command for Patroni
CMD ["patroni", "/etc/patroni/patroni.yml"]
