FROM postgres:16

# Switch to root for installing dependencies
USER root

# Install dependencies for Patroni and Consul integration
RUN apt-get update && apt-get install -y \
    python3-psycopg2 procps \
    patroni \
	python3-etcd3 \
	python3-consul \
    && apt-get clean

RUN chmod 700 /var/lib/postgresql/data

# Revert to the default postgres user
USER postgres

# Expose PostgreSQL and Patroni API ports
EXPOSE 5432 8008

# Set the default command for Patroni
CMD ["patroni", "/etc/patroni/patroni.yml"]
