FROM postgres:16

# Install dependencies for Patroni
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-setuptools curl && \
    pip3 install --no-cache-dir patroni[etcd] && \
    apt-get clean

# Expose PostgreSQL and Patroni API ports
EXPOSE 5432 8008

# Set the default command for the container
CMD ["patroni", "/etc/patroni/patroni.yml"]
