name: Build ASP.NET Docker Image

on:
  push:
    branches: [main]
    paths:
      - aspnet/**
      - .github/workflows/aspnet.yml
  pull_request:
    branches: [main]
    paths:
      - aspnet/**
      - .github/workflows/aspnet.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        aspnetcore_version: ["8.0", "9.0"]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push images
        uses: docker/build-push-action@v2
        with:
          context: ./aspnet
          file: ./aspnet/Dockerfile
          push: true
          tags: |
            ghcr.io/dtila/dockers/aspnet-chromium:${{ matrix.aspnetcore_version }}
          build-args: |
            ASPNETCORE_VERSION=${{ matrix.aspnetcore_version }}
