name: Build Nextcloud docker image

on:
  push:
    branches: [ "main" ]
    paths:
    - nextcloud/**
    - .github/workflows/nextcloud.yml
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./nextcloud
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # docker build --progress=plain --no-cache . -f Dockerfile -t ghcr.io/dtila/dockers/nexcloud-ha-crontab:latest
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./nextcloud
        file: ./nextcloud/Dockerfile
        push: true
        tags: ghcr.io/dtila/dockers/nexcloud-ha-crontab:latest
        