name: Build Patroni docker image

on:
  push:
    branches: [ "main" ]
    paths:
      - patroni/**
      - .github/workflows/patroni.yml
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 7 * * 1"  # Run every Monday at 7 AM

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./patroni
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        postgres_version: [16, 17]  # PostgreSQL versions to build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./patroni
        file: ./patroni/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64  # Multi-platform builds
        tags: ghcr.io/dtila/dockers/postgres-patroni:${{ matrix.postgres_version }}
        build-args: |
          POSTGRES_VERSION=${{ matrix.postgres_version }}
